import { BaseEntity } from './../../shared';

export class Pokemon implements BaseEntity {
    constructor(
        public id?: number,
        public abilities?: string,
        public againstBug?: number,
        public againstDark?: number,
        public againstDragon?: number,
        public againstElectric?: number,
        public againstFairy?: number,
        public againstFight?: number,
        public againstFire?: number,
        public againstFlying?: number,
        public againstGhost?: number,
        public againstGrass?: number,
        public againstGround?: number,
        public againstIce?: number,
        public againstNormal?: number,
        public againstPoison?: number,
        public againstPsychic?: number,
        public againstRock?: number,
        public againstSteel?: number,
        public againstWater?: number,
        public attack?: number,
        public baseEggSteps?: number,
        public baseHappiness?: number,
        public baseTotal?: number,
        public captureRate?: string,
        public classfication?: string,
        public defense?: number,
        public experienceGrowth?: number,
        public heightM?: number,
        public hp?: number,
        public japaneseName?: string,
        public name?: string,
        public percentageMale?: number,
        public pokedexNumber?: number,
        public spAttack?: number,
        public spDefense?: number,
        public speed?: number,
        public type1?: string,
        public type2?: string,
        public weightKg?: number,
        public generation?: number,
        public isLegendary?: number,
    ) {
    }
}
